### ISSUE TITLE
lambda not working or aditional config needed

### ISSUE THREAD

**Issue by georgebecerescu** [scottctaylor12/Red-Lambda#2]
Hi,

I've tried and reproduced the steps mentioned in your blog with just a minor variation: I used a kali instead of aws linux.
Nevertheless I couldn't get a callback when using Lambda as destination. It worked when I used payload with callback address directly on the IPv4 DNS name of the kali machine.
Is there some additional configuration needed or is the lambda code not working anymore? (i'm new to this setup).

Regards,

**Comment by scottctaylor12** [comment]
Apologies for the huge delay @georgebecerescu! It looks like some things changed with AWS Lambda since I published this project, so I just updated the project and did some testing with C2 frameworks. Since you mentioned Covenant in your message, I made sure to test with that framework and it works after my update :) The one thing to note is that you'll have to enable SSL when creating the http listener which involves uploading an SSL certificate. It can be any dummy self signed certificate, so I just created one with `openssl` and it worked out fine. 
Let me know if you have any further questions!
